import type { NextPage } from "next";
import Head from "next/head";
import { useGoogleOneTapLogin } from "@react-oauth/google";
import decode from "jwt-decode";
import useAuthStore from "../stores/authStore";
import Sidebar from "../components/Sidebar";
import Note from "../components/Note";
import { useState } from "react";

const Home: NextPage = () => {
  const { addUser, user } = useAuthStore();
  const [note, setNote] = useState([]);

  const Google: any = () => {
    useGoogleOneTapLogin({
      onSuccess: (res: any) => addUser(decode(res.credential)),
      onError: () => {
        console.log("error");
      },
    });

    return;
  };
  return (
    <div className="bg-bg">
      <Head>
        <title>listers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!user && <Google />}
      <section className="flex w-screen">
        <Sidebar setNote={setNote} />
        <Note note={note} />
      </section>
    </div>
  );
};

export default Home;
