import type { NextPage } from "next";
import Head from "next/head";
import { useGoogleOneTapLogin } from "@react-oauth/google";
import decode from "jwt-decode";
import useAuthStore from "../stores/authStore";
import Nav from "../components/Nav";
import Sidebar from "../components/Sidebar";
import Note from "../components/Note";

const Home: NextPage = () => {
  const { addUser, userProfile } = useAuthStore();

  const Google: any = () => {
    useGoogleOneTapLogin({
      onSuccess: (res: any) => addUser(decode(res.credential)),
      onError: () => {
        console.log("error");
      },
    });

    return;
  };
  return (
    <div className="bg-bg">
      <Head>
        <title>listers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!userProfile && <Google />}
      <Nav />
      <section className="flex">
        <Sidebar />
        <Note />
      </section>
    </div>
  );
};

export default Home;
